forecast_features = ['Total solar irradiance (W/m2)',
                     'Air temperature  (°C) ', 'Atmosphere (hpa)', 'Relative humidity (%)',
                     'Power (MW)', 'hour_sin', 'hour_cos', 'month_sin',
                     'month_cos', 'same_time_mean', 'same_time_std', 'same_time_max',
                     'same_time_min', 'same_weekday_mean', 'same_weekday_std',
                     'same_weekday_max', 'same_weekday_min', 'overall_mean', 'overall_std',
                     'overall_max', 'overall_min', 'lag_1', 'lag_2', 'lag_3', 'lag_4',
                     'lag_5', 'lag_6', 'lag_7', 'lag_8', 'diff_15min', 'diff_30min',
                     'diff_45min', 'diff_60min', 'diff_75min', 'diff_90min', 'diff_105min']

forecast_mlr_features = forecast_features + ['error_mlr', 'pred_mlr', 'same_time_mean_error_mlr',
                                             'same_time_std_error_mlr',
                                             'same_time_max_error_mlr',
                                             'same_time_min_error_mlr',
                                             'same_weekday_mean_error_mlr',
                                             'same_weekday_std_error_mlr',
                                             'same_weekday_max_error_mlr',
                                             'same_weekday_min_error_mlr',
                                             'overall_mean_error_mlr',
                                             'overall_std_error_mlr',
                                             'overall_max_error_mlr',
                                             'overall_min_error_mlr']

forecast_svr_features = forecast_features + ['error_svr', 'pred_svr', 'same_time_mean_error_svr',
                                             'same_time_std_error_svr',
                                             'same_time_max_error_svr',
                                             'same_time_min_error_svr',
                                             'same_weekday_mean_error_svr',
                                             'same_weekday_std_error_svr',
                                             'same_weekday_max_error_svr',
                                             'same_weekday_min_error_svr',
                                             'overall_mean_error_svr',
                                             'overall_std_error_svr',
                                             'overall_max_error_svr',
                                             'overall_min_error_svr']

forecast_lgb_features = forecast_features + ['error_lgb', 'pred_lgb', 'same_time_mean_error_lgb',
                                             'same_time_std_error_lgb',
                                             'same_time_max_error_lgb',
                                             'same_time_min_error_lgb',
                                             'same_weekday_mean_error_lgb',
                                             'same_weekday_std_error_lgb',
                                             'same_weekday_max_error_lgb',
                                             'same_weekday_min_error_lgb',
                                             'overall_mean_error_lgb',
                                             'overall_std_error_lgb',
                                             'overall_max_error_lgb',
                                             'overall_min_error_lgb']

forecast_mlp_features = forecast_features + ['error_mlp', 'pred_mlp', 'same_time_mean_error_mlp',
                                             'same_time_std_error_mlp',
                                             'same_time_max_error_mlp',
                                             'same_time_min_error_mlp',
                                             'same_weekday_mean_error_mlp',
                                             'same_weekday_std_error_mlp',
                                             'same_weekday_max_error_mlp',
                                             'same_weekday_min_error_mlp',
                                             'overall_mean_error_mlp',
                                             'overall_std_error_mlp',
                                             'overall_max_error_mlp',
                                             'overall_min_error_mlp']
